# Generated by Django 6.0.2 on 2026-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
